# This is a definition file for GitHub CI.

name: GitHub CI

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build_debian_stable:
    runs-on: ubuntu-latest
    container:
      image: debian:stable
    timeout-minutes: 120
    steps:
      - uses: actions/checkout@v1
      - name: prep
        run: |
             cp -R ./docker/builders/ci /scratch
             cp -R . /dcma
      - name: build
        run: |
             ( ( while true ; do sleep 225 ; printf '\n\n' ; df -h ; printf '\n\n' ; free -h ; printf '\n\n' ; done ) &)
             ./docker/builders/ci/implementation_ci_debian_stable.sh
      - name: test
        run: |
             ./integration_tests/Run.sh
      - name: create_appimage
        run: |
             ./scripts/extract_system_appimage.sh
             export DEBIAN_FRONTEND="noninteractive"
             apt-get update --yes
             apt-get install --yes --no-install-recommends coreutils findutils rsync openssh-client
             rm -rf ci_artifacts
             mkdir -pv ci_artifacts
             cp DICOMautomaton*AppImage DICOMautomaton-latest-x86_64.AppImage
             mv DICOMautomaton*AppImage ci_artifacts/
             find ci_artifacts/ -iname '*AppImage' -print -execdir bash -c 'sha256sum "$@" > "$@".sha256sum' bash '{}' \;
      - name: deploy_to_github
        uses: actions/upload-artifact@v2
        with:
          name: "DICOMautomaton-AppImage"
          if-no-files-found: error
          path: |
                ci_artifacts/DICOMautomaton-latest-x86_64.AppImage
                ci_artifacts/DICOMautomaton-latest-x86_64.AppImage.sha256sum
      - name: deploy_to_halclark_ca
        run: |
             echo "${{secrets.HALCLARKCA_DEPLOY_KEY}}" > deploy_key
             chmod 600 deploy_key
             rsync -avP -e 'ssh -i deploy_key -o StrictHostKeyChecking=no' ci_artifacts/ root@halclark.ca:/var/www/html/ci/

